<a href="https://colab.research.google.com/github/leticialandim/python_leticia/blob/master/BIG_A3_Classificacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="Universidade Presbiteriana Mackenzie">
</head>

<img src="http://meusite.mackenzie.br/rogerio/mackenzie_logo/UPM.2_horizontal_vermelho.jpg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->
NOME: LETICIA ALVES PAES LANDIM

MATRÍCULA: 10992059309

EAD_MACKENZIE_HIGIENOPOLIS

**Link do meu Colab:**
https://colab.research.google.com/drive/1u5DSaPQy7tq-suT4ietFFUFaaO6-3TcU?usp=sharing

# **Tarefa de Aprofundamento 3** 
## CASO: Controle de Qualidade de Peças de uma Indústria
---
<br>
<br>





A partir deste notebook você vai criar e avaliar diferentes modelos de classificação para prever a qualidade de peças de uma indústria. 

Em seguida, com base nos seus resultados, responda o **questionário do Moodle**. (**dica**: o questionário é de alternativas e as respontas irão ajudá-lo a verificar os seus resultados ao longo do programa). 

# Basic imports

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Exploração dos Dados



`pieces` é um data set para o controle de qualidade de peças produzidas por uma indústria. São empregadas quatro medidas (A, B, C e D) para o controle da qualidade das peças. As peças são então *Accept, Refurbish* ou *Reject* segundo o controle de qualidade (atributo `Quality`). A indústria ainda conta com 3 unidades para a produção dessas peças (atributo `Unit`). 

**Objetivo:** Seu objetivo é criar modelos supervisionados de classificação para predição da qualidade das peças e empregar o melhor modelo obtido (maior acuracidade) na predição da qualidade de novos casos. 



In [ ]:
df = pd.read_csv('http://meusite.mackenzie.br/rogerio/TIC/pieces1.csv')
df.head()

id    A    B    C    D    Quality Unit
0  559  4.9  3.1  1.5  0.1     Reject   SP
1  629  4.8  3.4  1.6  0.2     Reject   SP
2  192  6.7  2.5  5.8  1.8  Refurbish   RJ
3  359  7.6  3.0  6.6  2.1  Refurbish   RJ
4    9  4.9  3.1  1.5  0.1     Reject   RJ

## Inspecione os dados

In [ ]:
df

id    A    B    C    D    Quality Unit
0    559  4.9  3.1  1.5  0.1     Reject   SP
1    629  4.8  3.4  1.6  0.2     Reject   SP
2    192  6.7  2.5  5.8  1.8  Refurbish   RJ
3    359  7.6  3.0  6.6  2.1  Refurbish   RJ
4      9  4.9  3.1  1.5  0.1     Reject   RJ
..   ...  ...  ...  ...  ...        ...  ...
495  155  4.6  3.6  1.0  0.2     Reject   SP
496  120  6.9  3.2  5.7  2.3  Refurbish   RJ
497  321  6.7  3.1  5.6  2.4  Refurbish   RJ
498  448  5.6  3.0  4.1  1.3     Accept   SP
499  290  4.4  2.9  1.4  0.2     Reject   BH

[500 rows x 7 columns]

In [ ]:
df.describe()

id           A           B           C           D
count  500.0000  500.000000  491.000000  494.000000  496.000000
mean   323.2080    5.829600    3.076782    3.787449    1.235282
std    187.5734    0.817227    0.434519    1.749994    0.772550
min      0.0000    4.300000    2.000000    1.000000    0.100000
25%    152.7500    5.100000    2.800000    1.600000    0.300000
50%    323.0000    5.850000    3.000000    4.400000    1.300000
75%    486.5000    6.400000    3.400000    5.100000    1.800000
max    648.0000    7.900000    4.400000    6.900000    2.500000

## Preparação dos dados

Aqui você vai preparar o dado para o uso nos modelos. Você fará a seleção de atributos, tratamento de valores nulos, o encode dos dados, normalização e a separação dos dados de treinamento e teste.

### Seleção de Atributos

Elimine atributos que não fazem parte do treinamento.

In [ ]:
df = df.drop(columns= ['id'])
df.head()

A    B    C    D    Quality Unit
0  4.9  3.1  1.5  0.1     Reject   SP
1  4.8  3.4  1.6  0.2     Reject   SP
2  6.7  2.5  5.8  1.8  Refurbish   RJ
3  7.6  3.0  6.6  2.1  Refurbish   RJ
4  4.9  3.1  1.5  0.1     Reject   RJ

### Tratamento de Dados Ausentes

Verifique as presença de valores ausentes e, se houverem, subtitua pelo valor médio dos atributos.

In [ ]:
df.isnull().sum()

A          0
B          9
C          6
D          4
Quality    0
Unit       0
dtype: int64

In [ ]:
df = df.fillna(df.mean())

df.isnull().sum()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


A          0
B          0
C          0
D          0
Quality    0
Unit       0
dtype: int64

### Hot encode

Faça os *Hot Encodes* **necessários** dos dados. Lembre-se de verificar se de fato todos os dados categóricos precisam dessa transformação.

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

hot_encode = OneHotEncoder(handle_unknown='ignore') 
hot_encode = hot_encode.fit(df[['Unit']])

display(hot_encode.categories_)

df = pd.get_dummies(df, columns=['Unit'])

df.head()


[array(['BH', 'RJ', 'SP'], dtype=object)]

A    B    C    D    Quality  Unit_BH  Unit_RJ  Unit_SP
0  4.9  3.1  1.5  0.1     Reject        0        0        1
1  4.8  3.4  1.6  0.2     Reject        0        0        1
2  6.7  2.5  5.8  1.8  Refurbish        0        1        0
3  7.6  3.0  6.6  2.1  Refurbish        0        1        0
4  4.9  3.1  1.5  0.1     Reject        0        1        0

### Normalize os dados

Normalize os dados com o `StandardScaler` (melhor) ou a função `scale`.

$$ z_i = \frac{x_i - \bar{x}}{\sigma(x)}$$

E não esqueça de excluir dados não úteis ao treinamento. Depois de normalizar os dados os valores devem apresentar média próxima de 0 e desvio padrão próximo de 1.

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df.drop(columns= ["Quality"] ))
X = scaler.transform(df.drop(columns= ["Quality"] ))

X[0:5]

array([[-1.13864481,  0.05397611, -1.31636544, -1.47692919, -0.65777257,
        -0.57735027,  1.1100193 ],
       [-1.26113242,  0.7514042 , -1.25881814, -1.34683562, -0.65777257,
        -0.57735027,  1.1100193 ],
       [ 1.06613215, -1.34088009,  1.1581686 ,  0.73466146, -0.65777257,
         1.73205081, -0.90088523],
       [ 2.16852062, -0.17849993,  1.61854703,  1.12494216, -0.65777257,
         1.73205081, -0.90088523],
       [-1.13864481,  0.05397611, -1.31636544, -1.47692919, -0.65777257,
         1.73205081, -0.90088523]])

(Moodle) **Q1**. Após todas as transformações a soma dos valores absolutos ( `np.abs()` ) dos atributos referentes ao hot encode dos *BH*, *RJ* e *SP* são respectivamente?

*Empregue esta pergunta como ponto de checagem das suas transformações. Se não encontrar os seus valores dentre as alternativas há provavelmente um erro e você deve revisar as transformações.*

In [ ]:
print(np.abs(X[:,4]).sum())

459.12525524087647


In [ ]:
print(np.abs(X[:,5]).sum())

433.0127018922194


In [ ]:
print(np.abs(X[:,6]).sum())

497.2886485734416


### Conjuntos de Treinamento e Teste

Separe os dados de treinamento e teste (30%, estratificados pela variável objetivo e com random_state = 1984). Não empregue outros parâmetros não solicitados.


In [ ]:
from sklearn.model_selection import train_test_split

X = X
y = df.Quality

X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, test_size=0.3, random_state=1984)

print( X_train.shape, X_test.shape, y_train.shape, y_test.shape )

(350, 7) (150, 7) (350,) (150,)


# K-Vizinhos mais Próximos

Empregue o `GridSearchCV` com 5 partições e `scoring='accuracy'` para encontrar o melhor modelo entre os valores de $k$ de $4$ a $11$ e empregando as métricas euclidiana e manhattan. Verifique o modelo obtidos e o `classification_report` desse modelo.

Você pode querer empregar o modelo de código no final desse notebook que faz a mesma construção para Árvores de Decisão.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNeighborsClassifier().get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [ ]:
from sklearn.neighbors import DistanceMetric
from sklearn.model_selection import  GridSearchCV
from sklearn.metrics import classification_report
from sklearn import neighbors
from sklearn.metrics import confusion_matrix




In [ ]:
base_estimator = neighbors.KNeighborsClassifier()
param_grid = {'n_neighbors': [4,5,6,7,8,9,10,11], 'metric':['euclidean', 'manhattan']}

In [ ]:
clf = GridSearchCV( base_estimator, param_grid, cv=5, scoring='accuracy')
clf.fit(X_train, y_train)

print(clf.best_estimator_)

KNeighborsClassifier(metric='manhattan', n_neighbors=7)


In [ ]:
print()
print("Detailed classification report:")
print()
y_pred = clf.predict( X_test )
print(classification_report( y_test, y_pred))
print()


Detailed classification report:

              precision    recall  f1-score   support

      Accept       0.88      0.98      0.93        47
   Refurbish       0.98      0.89      0.93        55
      Reject       1.00      1.00      1.00        48

    accuracy                           0.95       150
   macro avg       0.95      0.96      0.95       150
weighted avg       0.96      0.95      0.95       150




(Moodle) **Q2** Qual o melhor modelo de Knn obtido e qual a sua acuracidade? 

(Moodle) **Q3** Qual classe teve os elementos mais erroneamente classificados? 

**R2:** O melhor modelo de Knn obtido foi 7. E acuracidade: 0.95.
**R3:** a classe que teve os elementos mais erroneamente classificados foi: Accept e Refurbish.

# Regressão Logística

Empregue o `GridSearchCV` com 5 partições e `scoring='accuracy'` para avaliar o modelo de regressão logística. Empregue somente os parâmetros padrão do `sciki-learn` para regressão logística, para isso basta empregar `param_grid = {}`. Verifique os resultados obtidos desse modelo com o `classification_report`. 

Você pode querer empregar o modelo de código no final desse notebook que faz a mesma construção para Árvores de Decisão.

In [ ]:
from sklearn.linear_model import LogisticRegression
LogisticRegression().get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report

In [ ]:
base_estimator = LogisticRegression()
param_grid = {}

clf = GridSearchCV( base_estimator, param_grid, cv=5, scoring='accuracy')
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(), param_grid={},
             scoring='accuracy')

In [ ]:
print(clf.best_estimator_)
print()
print("Detailed classification report:")
print()


LogisticRegression()

Detailed classification report:



In [ ]:
Y_pred = clf.predict( X_test)
print(classification_report(y_test, Y_pred))
print()

              precision    recall  f1-score   support

      Accept       0.92      1.00      0.96        47
   Refurbish       1.00      0.93      0.96        55
      Reject       1.00      1.00      1.00        48

    accuracy                           0.97       150
   macro avg       0.97      0.98      0.97       150
weighted avg       0.98      0.97      0.97       150




In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_test, Y_pred)
accuracy

0.9733333333333334

In [ ]:
cm = confusion_matrix(y_test, Y_pred)
cm

array([[47,  0,  0],
       [ 4, 51,  0],
       [ 0,  0, 48]])

(Moodle) **Q4** Qual a acuracidade do modelo de regressão logística e qual classe teve mais falsos positivos? 

**R4:**: a acuracidade é 0.97, e a classe com mais falsos positivos foi:  Refurbish e Accept igualmente.

# Aplicando o melhor Modelo

Empregue o melhor modelo obtido acima para estimar a qualidade das peças das 10 peças do conjunto abaixo.

In [ ]:
df_new = pd.read_csv('http://meusite.mackenzie.br/rogerio/TIC/pieces_new.csv')
df_new 

id    A    B    C    D Unit
0  182  5.5  2.6  4.4  1.2   SP
1  345  5.8  2.7  4.1  1.0   SP
2   42  5.1  3.5  1.4  0.2   SP
3   37  6.3  2.5  4.9  1.5   BH
4   61  6.0  3.0  4.8  1.8   RJ

## Preparação dos Dados

Lembre-se, as mesmas operações feitas com os dados de treinamento precisarão ser feitas aqui também. 

### Seleção de Atributos 

In [ ]:
df_new = df_new.drop(columns= ['id'])
df_new

A    B    C    D Unit
0  5.5  2.6  4.4  1.2   SP
1  5.8  2.7  4.1  1.0   SP
2  5.1  3.5  1.4  0.2   SP
3  6.3  2.5  4.9  1.5   BH
4  6.0  3.0  4.8  1.8   RJ

### Hot encode  

In [ ]:
hot_encode = hot_encode.fit(df_new[['Unit']])
display(hot_encode.categories_)

[array(['BH', 'RJ', 'SP'], dtype=object)]

In [ ]:
df_new = pd.concat( [ df_new.drop(columns='Unit'), pd.DataFrame(hot_encode.transform(df_new[['Unit']]).toarray(), columns = list( hot_encode.categories_[0] )) ], axis=1 ) 
df_new.head()

A    B    C    D   BH   RJ   SP
0  5.5  2.6  4.4  1.2  0.0  0.0  1.0
1  5.8  2.7  4.1  1.0  0.0  0.0  1.0
2  5.1  3.5  1.4  0.2  0.0  0.0  1.0
3  6.3  2.5  4.9  1.5  1.0  0.0  0.0
4  6.0  3.0  4.8  1.8  0.0  1.0  0.0

### Normalize os dados

In [ ]:
X_new = scaler.fit(df_new)
X_new = scaler.transform(df_new)
X_new 

array([[-0.5814019 , -0.72000341,  0.37147964,  0.11058147, -0.5       ,
        -0.5       ,  0.81649658],
       [ 0.14535047, -0.44307902,  0.13930487, -0.25802342, -0.5       ,
        -0.5       ,  0.81649658],
       [-1.55040507,  1.77231608, -1.95026813, -1.73244298, -0.5       ,
        -0.5       ,  0.81649658],
       [ 1.35660443, -0.9969278 ,  0.7584376 ,  0.6634888 ,  2.        ,
        -0.5       , -1.22474487],
       [ 0.62985206,  0.38769414,  0.68104601,  1.21639614, -0.5       ,
         2.        , -1.22474487]])

In [ ]:
scaler.transform(df_new)

array([[-0.5814019 , -0.72000341,  0.37147964,  0.11058147, -0.5       ,
        -0.5       ,  0.81649658],
       [ 0.14535047, -0.44307902,  0.13930487, -0.25802342, -0.5       ,
        -0.5       ,  0.81649658],
       [-1.55040507,  1.77231608, -1.95026813, -1.73244298, -0.5       ,
        -0.5       ,  0.81649658],
       [ 1.35660443, -0.9969278 ,  0.7584376 ,  0.6634888 ,  2.        ,
        -0.5       , -1.22474487],
       [ 0.62985206,  0.38769414,  0.68104601,  1.21639614, -0.5       ,
         2.        , -1.22474487]])

## Predição

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score

In [ ]:
clf = neighbors.KNeighborsClassifier(n_neighbors=3, metric = 'euclidean')
clf.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [ ]:
y_pred= clf.predict(X_new )

In [ ]:
df_new['Prediction'] = y_pred 
df_new

A    B    C    D   BH   RJ   SP Prediction
0  5.5  2.6  4.4  1.2  0.0  0.0  1.0     Accept
1  5.8  2.7  4.1  1.0  0.0  0.0  1.0     Accept
2  5.1  3.5  1.4  0.2  0.0  0.0  1.0     Reject
3  6.3  2.5  4.9  1.5  1.0  0.0  0.0     Accept
4  6.0  3.0  4.8  1.8  0.0  1.0  0.0  Refurbish

(Moodle) **Q5** Quais as classes obtidas com o melhor modelo para os cinco novos casos? 

**R5:** as classes são Accept, Accept, Reject, Accept, Refurbish.



# Apêndice: Árvore de Decisão (RESOLVIDO)

Este é apenas um exemplo empregando o `GridSearchCV` com 5 partições e `scoring='accuracy'` para avaliar um modelo de Árvore de Decisão com diferentes parâmetros. Você irá estudar mais detalhtes do modelo de Árvore de Decisão na próxima trilha. Mas ele é um classificador, assim como o modelo de K-Vizinhos mais Próximos e a Regressão Logística, e o uso desse estimador segue os mesmos moldes desses estimadores. Você pode assim aplicá-lo do mesmo modo. 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier().get_params()

In [ ]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

base_estimator = DecisionTreeClassifier()

param_grid = {'criterion': ['gini', 'entropy'], 'max_depth': [ None, 3 ]}

clf = GridSearchCV(base_estimator, param_grid, cv=5, scoring='accuracy')
clf.fit(X_train, y_train)

# print(clf.cv_results_)
print(clf.best_estimator_)

print()
print("Detailed classification report:")
print()
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))
print()